# Generated by Django 3.0.2 on 2021-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0002_auto_20210412_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='posterLink',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
