# Generated by Django 3.0.2 on 2021-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0004_auto_20210412_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
