# Generated by Django 3.0.2 on 2021-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0006_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
