# Generated by Django 3.0.2 on 2021-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0007_auto_20210414_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
