# Generated by Django 3.0.2 on 2021-04-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0009_movielist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commented_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commented_movie', to='movietopia.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
