# Generated by Django 3.0.2 on 2021-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0011_comment_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=120),
        ),
    ]
