# Generated by Django 3.0.2 on 2021-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietopia', '0014_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posterLow',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
